### ISSUE TITLE
Kibana Data

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#403]
Currently I am creating spreadsheets which highlight consultant activity by copy and pasting information from Kibana and then modifying it in Excel.

Kibana limits me to only copying 1000 rows at a time - if I change it to display any more than that, Kibana runs very slowly and often can't complete the search.

Specifically, I am trying to pull off some data for Alex about Ruby developers on the app and there are roughly 9000 results I want to put into a table and analyse, what's the best way of me downloading all 9000 rows of data?

I'm not particularly familiar or savvy with the Visualize tab on Kibana, and whenever I want to create a table I end up displaying precisely nothing.

I want a table showing the fields: Location, Headline, Full Name and Email address for all the Ruby developers in our database and then would like to download this as a CSV file or any similar format where I can then manipulate it in Excel.

Help me Obi-Wan Kenobi, you're my only hope.

**Comment by nelsonic** [comment]
@Adam-JF Kibana does not *yet* have a way to bulk-export data (*as CSV*) 
there is an open issue on the Kibana GitHub repo and its marked as "**P1**" (*top priority*): https://github.com/elastic/kibana/issues/1992 ... but this does not help you *today*.

@SimonLab can you please dig out the script you wrote to backup the ElasticSearch database and send it to me? *thanks*.

**Comment by SimonLab** [comment]
@Adam-JF I'm going to have a look at it. Otherwise is https://github.com/FAC-GM/data-copy/blob/master/helpers/copy-candidates.js what you want @nelsonic ?

**Comment by SimonLab** [comment]
I was looking at [electron](http://electron.atom.io/), it can allow us to create a desktop app which allow a user to export the data to a csv file. The advantage of it is that we don't have to create another endpoint on the app and we don't have to manage authentication/authorization because the electron app doesn't have to be hosted on a server. I just played with a simple hello app for now but I understand that we can reuse some nodejs and npm packages easily. I think an electron app can be a nice temporary solution for exporting data as we have already a lot of work/code to manage on the app. What do you think @nelsonic?

**Comment by nelsonic** [comment]
@SimonLab `electron` *could* an option, but we need to time-box it.
Is there a simpler solution?
