### ISSUE TITLE
Add Adam Hemsley

### ISSUE THREAD

**Issue by Adam-JF** [FAC-GM/source-code#480]
I added the Adam Hemsley LI account and user details to the app and Alex was still unable to login.

His email address is:
ahemsley2@mac.com

Does this need to be approved?

Alternatively, if I change the LI name in the user details will the Alex Hemsley app account be able to pull in information from the Adam Hemsley LI account?

**Comment by SimonLab** [comment]
I'm not sure I understand completely what you want to achieve with Adam's account. If you just want to connect normally to the application the email address needs to be a gmail address and I'm not sure it is one.

Otherwise using the extension should work with other accounts. I will check if there are some side effects and list what the application needs for an account with multiple LI to work.
